### PR TITLE
Avoid setting display block when an element is about to be shown again

### PR DESCRIPTION
**Pull request by sreucherand**
I have got this scenario. I had an element, originally with a `display: table` in css. If it was hidden after I applied a `hidden(el, true)`, I did not expect to get a `display: block` when I wanted it to be visible again.

What my code is doing, just remove the `display` property from the style attribute when you apply `hidden(el, false)`.

For me, it fits a bit better in the hidden philosophy. What do you think?

### CODE REVIEW

**Comment by TehShrike** [comment]
It makes sense to me.  What do you think @Raynos?

If @Raynos is fine with it, would you be willing to add tests to assert the new behavior @sreucherand?

**Comment by Raynos** [comment]
Sure;

**Comment by sreucherand** [comment]
@TehShrike @Raynos Thanks for your feedback! I have added the corresponding test.

**Comment by TehShrike** [comment]
lgtm!

**Comment by TehShrike** [comment]
@Raynos will have to hit the publish button to get this new minor version to npm.

**Comment by Raynos** [comment]
@TehShrike I added you as an owner :)

**Comment by TehShrike** [comment]
Cool!  Published as 1.1.0.

**Pull request merged**
